### ISSUE TITLE
Not Proper Logic

### ISSUE THREAD

**Issue by Shilpi75** [shivaya-sinha/PageRefresher#1]
Hey 
Your logic is wrong. Also, there are some errors.

**Comment by shivaya-sinha** [comment]
Yeah, you're right. Actually, I'm learning to program.Thank you for helping me. Since you have corrected the errors I'll close this issue. @Shilpi75 :heart:

**Comment by shivaya-sinha** [comment]
Glad to help :)

**Comment by Shilpi75** [comment]
Glad to help :) <3
